apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - name: ui
      nodePort: 32001
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: slave
      nodePort: 32002
      port: 50000
      protocol: TCP
    - name: http
      nodePort: 32003
      port: 80
      targetPort: 8080
  selector:
    app: jenkins