apiVersion: v1
kind: Service
metadata:
  name: fellipe-nginx
  namespace: teste 
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32000
    port: 80
    targetPort: server
    protocol: TCP
  selector:
    app: fellipe-nginx
