apiVersion: v1
kind: Service
metadata:
  name: fellipe-nginx
  namespace: teste 
spec:
  type: NodePort
  ports:
  - port: 32000
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: fellipe-nginx
